[2025-03-19T17:30:55.312+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: faud_detection_pipeline.store_data_hdfs scheduled__2023-10-13T12:00:00+00:00 [queued]>
[2025-03-19T17:30:55.351+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: faud_detection_pipeline.store_data_hdfs scheduled__2023-10-13T12:00:00+00:00 [queued]>
[2025-03-19T17:30:55.353+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-03-19T17:30:55.397+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): store_data_hdfs> on 2023-10-13 12:00:00+00:00
[2025-03-19T17:30:55.411+0000] {standard_task_runner.py:57} INFO - Started process 34710 to run task
[2025-03-19T17:30:55.427+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'faud_detection_pipeline', 'store_data_hdfs', 'scheduled__2023-10-13T12:00:00+00:00', '--job-id', '2363', '--raw', '--subdir', 'DAGS_FOLDER/dag_1.py', '--cfg-path', '/tmp/tmp8t3lmuxf']
[2025-03-19T17:30:55.438+0000] {standard_task_runner.py:85} INFO - Job 2363: Subtask store_data_hdfs
[2025-03-19T17:30:55.643+0000] {task_command.py:415} INFO - Running <TaskInstance: faud_detection_pipeline.store_data_hdfs scheduled__2023-10-13T12:00:00+00:00 [running]> on host 0009f5fb76aa
[2025-03-19T17:30:55.886+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='faud_detection_pipeline' AIRFLOW_CTX_TASK_ID='store_data_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2023-10-13T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-13T12:00:00+00:00'
[2025-03-19T17:30:55.889+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-19T17:30:55.896+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker cp /tmp/transactions.csv namenode:/tmp/transactions.csv && docker cp /tmp/customers.csv namenode:/tmp/customers.csv && docker cp /tmp/external_data.csv namenode:/tmp/external_data.csv && docker exec namenode bash -c "hdfs dfs -mkdir -p /data/transactions && hdfs dfs -mkdir -p /data/customers && hdfs dfs -mkdir -p /data/external_data && hdfs dfs -put -f /tmp/transactions.csv /data/transactions/transactions.csv && hdfs dfs -put -f /tmp/customers.csv /data/customers/customers.csv && hdfs dfs -put -f /tmp/external_data.csv /data/external_data/external_data.csv && rm -rf /tmp/transactions.csv /tmp/customers.csv /tmp/external_data.csv"']
[2025-03-19T17:30:55.920+0000] {subprocess.py:86} INFO - Output:
[2025-03-19T17:31:20.967+0000] {subprocess.py:93} INFO - 2025-03-19 17:31:20,962 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
[2025-03-19T17:31:27.840+0000] {subprocess.py:93} INFO - 2025-03-19 17:31:27,837 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
[2025-03-19T17:31:33.558+0000] {subprocess.py:93} INFO - 2025-03-19 17:31:33,550 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
[2025-03-19T17:31:35.156+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-19T17:31:35.235+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=faud_detection_pipeline, task_id=store_data_hdfs, execution_date=20231013T120000, start_date=20250319T173055, end_date=20250319T173135
[2025-03-19T17:31:35.957+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-19T17:31:36.678+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
