[2025-03-19T12:25:50.516+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_pipeline.store_data_hdfs scheduled__2023-10-09T06:00:00+00:00 [queued]>
[2025-03-19T12:25:50.530+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_pipeline.store_data_hdfs scheduled__2023-10-09T06:00:00+00:00 [queued]>
[2025-03-19T12:25:50.531+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-03-19T12:25:50.554+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): store_data_hdfs> on 2023-10-09 06:00:00+00:00
[2025-03-19T12:25:50.563+0000] {standard_task_runner.py:57} INFO - Started process 6618 to run task
[2025-03-19T12:25:50.569+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'fraud_detection_pipeline', 'store_data_hdfs', 'scheduled__2023-10-09T06:00:00+00:00', '--job-id', '670', '--raw', '--subdir', 'DAGS_FOLDER/dag_1.py', '--cfg-path', '/tmp/tmpl675scuv']
[2025-03-19T12:25:50.573+0000] {standard_task_runner.py:85} INFO - Job 670: Subtask store_data_hdfs
[2025-03-19T12:25:50.684+0000] {task_command.py:415} INFO - Running <TaskInstance: fraud_detection_pipeline.store_data_hdfs scheduled__2023-10-09T06:00:00+00:00 [running]> on host 0009f5fb76aa
[2025-03-19T12:25:50.820+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fraud_detection_pipeline' AIRFLOW_CTX_TASK_ID='store_data_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2023-10-09T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-09T06:00:00+00:00'
[2025-03-19T12:25:50.824+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-19T12:25:50.826+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker cp /tmp/transactions.json namenode:/tmp/transactions.json && docker cp /tmp/customers.json namenode:/tmp/customers.json && docker cp /tmp/external_data.json namenode:/tmp/external_data.json && rm -rf /tmp/external_data.json  && rm -rf /tmp/customers.json  && rm -rf /tmp/transactions.json  && docker exec namenode bash -c "hdfs dfs -mkdir -p /data && hdfs dfs -put -f /tmp/transactions.json /data/transactions.json && hdfs dfs -put -f /tmp/customers.json /data/customers.json && hdfs dfs -put -f /tmp/external_data.json /data/external_data.json && rm -rf /tmp/customers.json  && rm -rf /tmp/customers.json  && rm -rf /tmp/external_data.json "']
[2025-03-19T12:25:50.846+0000] {subprocess.py:86} INFO - Output:
[2025-03-19T12:25:50.907+0000] {subprocess.py:93} INFO - lstat /tmp/transactions.json: no such file or directory
[2025-03-19T12:25:50.914+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-19T12:25:50.933+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T12:25:50.943+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=fraud_detection_pipeline, task_id=store_data_hdfs, execution_date=20231009T060000, start_date=20250319T122550, end_date=20250319T122550
[2025-03-19T12:25:50.981+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 670 for task store_data_hdfs (Bash command failed. The command returned a non-zero exit code 1.; 6618)
[2025-03-19T12:25:51.026+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-19T12:25:51.181+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
